
VERSION_FILE = './version'

# service bind ip address and port
LISTEN = '0.0.0.0'
PORT = 8888

# development env
DEBUG = True
LOG_DEBUG = False

# Database configuration
DATABASE_CONFIG = '../../config.json'
